name: chirpp_gpu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - cudatoolkit
  - cuda-nvcc
  - pip
  - postgresql
  - pip:
      - torch
variables:
  PYTHONNOUSERSITE: '0'
