name: chirpp_gpu
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - postgresql
  - gcc
  - gxx
  - pip:
      - torch
variables:
  PYTHONNOUSERSITE: '0'