name: chirpp_cpu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch-cpu
  - pip
  - python=3.10
  - pip:
      - pandas
      - Levenshtein
      - spacy
      - medspacy
      - sentence-transformers
      - transformers==4.30
      - tokenizers
      - spacy_transformers
      - sentencepiece
      - safetensors
      - pyyaml
      - python-dateutil
      - openpyxl
      - SQLAlchemy
variables:
  PYTHONNOUSERSITE: '0'