# -*- coding: utf-8 -*-
"""chirpp_post_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ASqF0I3AanFCi3G5dIKOJH8Ef2fPILmJ
"""

import openpyxl
from openpyxl.styles import PatternFill
from openpyxl import load_workbook

def postprocess(
    filename, sheetname,
    phac_nar, NO1, BP1, DISP, IN, sub, sd1, SPORTS,
    area_col_index, io_col_index, bp1_index, no1_index, in_index,
    indoor, outdoor
):

    """
    Post processes an Excel workbook

    This function iterates over rows of a selected sheet in the workbook. If specific conditions are met,
    it modifies the cell values in place. It also applies color fill to cells with None values in specific columns.
    In the end, the modified workbook is saved back to the disk.

    :param filename: Path to the Excel workbook.
    :type filename: str
    :param sheetname: Name of the sheet in the workbook to be processed.
    :type sheetname: str
    :param phac_nar: Column letter for PHAC_NAR.
    :type phac_nar: str
    :param NO1: Column letter for NO1.
    :type NO1: str
    :param BP1: Column letter for BP1.
    :type BP1: str
    :param DISP: Column letter for DISP.
    :type DISP: str
    :param IN: Column letter for IN.
    :type IN: str
    :param sub: Column letter for SUB.
    :type sub: str
    :param sd1: Column letter for SD1.
    :type sd1: str
    :param SPORTS: Column letter for SPORTS.
    :type SPORTS: str
    :param area_col_index: Zero-based index for the AREA column.
    :type area_col_index: int
    :param io_col_index: Zero-based index for the I/O column.
    :type io_col_index: int
    :param bp1_index: Zero-based index for the BP1 column.
    :type bp1_index: int
    :param no1_index: Zero-based index for the NO1 column.
    :type no1_index: int
    :param in_index: Zero-based index for the IN column.
    :type in_index: int
    :param indoor: List of values considered as indoor for the AREA column.
    :type indoor: list of int
    :param outdoor: List of values considered as outdoor for the AREA column.
    :type outdoor: list of int
    :return: None. The function works by modifying the workbook in place.

    """

    workbook = openpyxl.load_workbook(filename)
    sheet = workbook[sheetname]


    yellow_fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")

    for row in sheet.iter_rows(min_row=2):
        column1_value = row[no1_index].value
        column2_value = row[bp1_index].value

        if column1_value == 71 and column2_value == 900:
            row[in_index].value = 16

    columns = [phac_nar, NO1, BP1, DISP, IN, sub, sd1, SPORTS]

    for i in columns:
        col = sheet[i]
        for cell in col:
            if cell.value is None:
                cell.fill = yellow_fill

    for row in sheet.iter_rows(min_row=2, min_col=area_col_index, max_col=area_col_index):
        area_cell = row[0]
        io_cell = row[0].offset(column=io_col_index - area_col_index)


        if area_cell.value in indoor:
            io_cell.value = 1
        elif area_cell.value in outdoor:
            io_cell.value = 2

    workbook.save(filename)

postprocess(
    'C:/Users/alyssia naran/Downloads/no_highlight.xlsx', 'Sheet2',
    'S', 'U', 'V', 'AC', 'AD', 'AH', 'AJ', 'AO',
    14, 12, 21, 20, 29,
    [11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 31, 34, 35, 36, 77, 92],
    [43, 44, 51, 52, 53, 55, 56, 58, 61, 62, 63, 81, 82, 83, 84, 85, 91]
)