# These will be used in filter section need to create pydantic section and load them
# in columns dynamically

SYMBOL_MAP = {"gt": ">", "lt": "<", "gte": ">=", "lte": "<=", "eq": "=", "neq": "≠", "like": "Contains",
              "not_like": "Does Not Contain", "in": "In List", "not_in": "Not In List"}

TABLE_CONFIG = {"visits": {"label": "Visits", "columns": {
    "sex": {"label": "Sex", "type": "categorical", "values": ["M", "F"], "code_labels": {"M": "Male", "F": "Female"},
            "comparators": ["eq", "neq"]},
    "age": {"label": "Age", "type": "integer", "comparators": ["gt", "lt", "gte", "lte", "eq", "neq"], },
    "arrival_date": {"label": "Arrival Date", "type": "date", "comparators": ["gt", "lt", "gte", "lte", "eq", "neq"], },
    "ctas": {"label": "CTAS", "type": "categorical", "values": [1, 2, 3, 4, 5],
             "code_labels": {1: "Life or limb threatening", 2: "Potential thread to life or limb",
                             3: "Could progress to serious conditions", 4: "Conditions that require intervention",
                             5: "Stable Non-urgent"}, "comparators": ["gt", "lt", "gte", "lte", "eq", "neq"], },
    "los": {"label": "Length of Stay", "type": "numerical", "comparators": ["gt", "lt", "gte", "lte"], },
    "diagnosis": {"label": "Diagnosis", "type": "categorical", "comparators": ["like", "not_like"], },
    "chief_complaint": {"label": "Chief Complaint", "type": "categorical", "comparators": ["like", "not_like"], },
    "disposition": {"label": "Disposition", "type": "categorical", "comparators": ["like", "not_like"], }}},
                "problems": {"label": "Problems", "columns": {
                    "problem": {"label": "Problem", "type": "categorical", "comparators": ["like", "not_like"], }}},

                "chirpp_report": {"label": "CHIRPP Cases", "columns": {
                    "intent": {"label": "Intent", "type": "categorical", "values": [10, 11, 12, 13, 14, 15, 16, 19],
                        "code_labels": {10: "Accident", 11: "Self Harm", 12: "Sexual Abuse/Assault",
                                        13: "Parental Abuse/Neglect", 14: "Partner Abuse", 15: "Assault (Non-Sexual)",
                                        16: "Undetermined", 19: "Police/Other/Medical"}, "comparators": ["eq", "neq"]},
                    "am_pm": {"label": "AM or PM", "type": "categorical", "values": ["a", "p"],
                        "code_labels": {"a": "AM", "p": "PM"}, "comparators": ["eq", "neq"]},
                    "injury_date": {"label": "Injury Date", "type": "integer",
                        "comparators": ["gt", "lt", "gte", "lte", "eq", "neq"], },
                    "i_o": {"label": "Inside/Outside", "type": "categorical", "values": [1, 2],
                        "code_labels": {1: "Inside", "2": "Outside"}, "comparators": ["eq", "neq"], },
                    "location": {"label": "Location", "type": "categorical",
                        "values": [11, 12, 13, 14, 19, 21, 22, 23, 24, 29, 31, 32, 33, 39, 41, 42, 43, 44, 45, 49, 51,
                                   52, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 79, 81, 82, 91, 92, 93, 94, 95, 96,
                                   97, 98, 109, 111, 112, 119, 121, 131, 141, 142, 143, 144, 145, 149, 150],
                        "code_labels": {11: "patients' own farm house",
                            21: "farm house belonging to someone else (including relatives)",
                            12: "patients' own home apartment, condo",
                            22: "home, apartment or condo belonging to someone else",
                            13: "dormitory, school boarding or hostel where the patient is staying",
                            23: "someone else's dormitory, school boading or hostel",
                            14: "patient's trailer home or motorhome", 24: "someone else's trailer home or motor home",
                            19: "patients' cottage", 29: "someone else's cottage",
                            31: "institutional home, shelter, group home or halfway home",
                            32: "retirement or nursing home", 33: "prison, jail or other detention centers",
                            39: "other residential institutions for example ronald mac donald house",
                            41: "daycare or preschool", 42: "school or kindergarden",
                            43: "tertiary adult edication for examplel university or military college",
                            44: "public administration building like city hall, fire/police station, courthouse",
                            45: "place for arts like museum, performance halls, concert hall, library",
                            49: "other kinds of institutions like church, military base", 51: "hospital",
                            52: "community health center, detox center, dental office, doctor's office (not in a hospital)",
                            61: "amusement park", 62: "public park",
                            63: "aquatic center, like a water park or swimming pool", 64: "stadium or arena for sports",
                            65: "community center",
                            66: "fitness center, gym (not in school), martial arts center/dojo, dance studio, ballet school",
                            67: "race track for motor sports and horseback",
                            68: "other land based sports facility like golf couse, skate park (not ice skating), rodeo grounds",
                            69: "water based sports like yatch club, marina, fishing lodge, kayak club, rowing club",
                            70: "snow/ice based sports facility like ski resort, ski cabin",
                            71: "skate park for ice skating",
                            79: "facility for recration like arcade, bowling alley, bingo hall", 81: "highway",
                            82: "other roads like alley, lane, bus stop",
                            91: "shop, shopping mall or other commerce centers", 92: "restaurants, bars, coffee shops",
                            93: "entertainment place like bar, night club, casino, strip club",
                            94: "airport, train/bus/subway stattion ferry terminal",
                            95: "service or gas station for automotives", 96: "warehouse", 97: "office building",
                            98: "hotel/motel/bed and breakfast, resort",
                            109: "other commercial and trade area like bank, laundromat, funeral home, veterenerian office",
                            141: "remote undevloped place, swamp, snowmobile track",
                            142: "railway tracks not including station", 143: "camp grounds, trailer park",
                            144: "onboard a vehicle like plane, train, bus, ship, ferry",
                            111: "construction/demolotion site", 112: "factory, mill, manufacturing site",
                            119: "other industrial area", 121: "mine, oil or gas well, quarry, sandpit",
                            131: "farm, barn, coop but exclduing the farmhouse"}, "comparators": ["in", "not_in"]},
                    "area": {"label": "Area", "type": "categorical",
                        "values": [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 36, 41, 42, 43,
                                   44, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 71, 72, 73, 74, 75, 76, 77,
                                   78, 81, 82, 83, 84, 85, 91, 92, 99],
                        "code_labels": {11: "bathroom, toilet, change room", 12: "bedroom",
                            13: "classroom, daycare indoors", 14: "dorm room",
                            15: "hall, foyer, waiting room, emergency room", 16: "kitchen", 17: "laundry room",
                            18: "dining area, cafeteria", 19: "living room, rec room, den", 20: "office",
                            21: "basement", 22: "spectator area in a church, theatre",
                            31: "garage, carport, parking lot", 32: "workshop",
                            33: "agricultural buildings like silo or piggery", 34: "stable, barn", 35: "shed",
                            36: "other specialized buildings like greenhouse", 41: "escalator, elevator", 42: "stairs",
                            43: "porch, deck balcony, veranda", 44: "roof",
                            51: "paved road (assume paved unless specified)", 52: "unpaved road", 53: "driveway",
                            54: "parking lot", 55: "sidewalk, bus stop", 56: "median, strip, traffic island",
                            57: "tunnel, trench, ditch", 58: "bike path", 59: "playground",
                            60: "garden, backyard, school yard", 61: "pasture, field, other outdoor animal area",
                            62: "cliff, rock face", 63: "trails", 71: "gym, fitness room, yoga studio",
                            72: "sports field, track, including indoor spaces", 73: "tennis, squash etc. court",
                            74: "swimming pool", 75: "ice rink", 76: "concrete rink for skating",
                            77: "locker room, change room", 78: "splash pad", 81: "beach, shore, riverbank", 82: "dam",
                            83: "river, lake, creek, pond", 84: "sea, ocean", 85: "wharf, dock pier",
                            91: "other exterior space, crawlspace, under porch, veranda",
                            92: "other interior space like storage, attic etc."}, "comparators": ["in", "not_in"]},
                    "place": {"label": "Place", "type": "categorical", "comparators": ["like", "not_like"], },
                    "sd_all": {  # This key doesn't exist in DB, it's our virtual key
                        "label": "Safety Devices", "type": "categorical",
                        "virtual_group": ["sd1", "sd2", "sd3", "sd4", "sd5"],
                        "values": [-1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 19],
                        "code_labels": {-1: "Unknown", 0: "No Device", 2: "Helmet", 3: "Sports Padding",
                                        4: "Protective Clothing or Boots", 5: "Eyewear", 6: "Seatbelt", 7: "Carseat",
                                        8: "Airbag (Deployed)", 9: "Not Specified", 10: "Life Jacket", 11: "Hard Hat",
                                        12: "Mouth Guard", 19: "Baby Gate", }, "comparators": ["in", "not_in"]},
                    "sports_code": {"label": "Sports Code", "type": "categorical", "values": [1, 2, 3, 4],
                        "code_labels": {1: "yes", 2: "no", 3: "unknown", 4: "not applicable"},
                        "comparators": ["in", "not_in", "eq", "neq"]},

                    "no_all": {"label": "Nature of Injury", "type": "categorical",
                        "virtual_group": ["no1", "no2", "no3"],
                        "values": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 31, 32, 33,
                                   34, 35, 36, 37, 41, 42, 43, 50, 51, 52, 53, 60, 70, 75, 76, 77, 99],
                        "code_labels": {10: "superficial bruises, abrasions", 11: "open wound including minor cuts",
                            12: "fracture", 13: "dislocation", 14: "sprain or strain", 15: "injury to nerve",
                            16: "injury to blood vessel like hemorrhage", 17: "injury to muscle or tendon live rupture",
                            18: "crushing injury", 19: "traumatic amputation",
                            20: "external burn or corrosion (no eye inj)", 21: "frostbite",
                            22: "insect, animal or human bite", 23: "electrical injury",
                            24: "eye injury including burn or corrosion", 25: "dental injury",
                            26: "injury to internal organs excluding inner ear", 27: "soft tissue injury",
                            31: "foreign body in external eys", 32: "foreign body in ear canal",
                            33: "foreing body in nose", 34: "foreign body in respiratory tract excluding nose",
                            35: "foreign body in digestive tract", 36: "foreign body in genital, unrinary tract",
                            37: "foreing body in soft tissue including splinters", 41: "minor head injury",
                            42: "concussion", 43: "intracranial injury", 50: "poisoning or toxic effect",
                            51: "drowning, near drowning or immersion", 52: "asphixia or other treath to breathing",
                            53: "overexertion, heat/cold stress", 60: "multiple injuries of more than one nature",
                            70: "no injuries", 75: "pulled elbow", 99: "unspecified or no injury",
                            76: "internal causitic burn", 77: "penetrating wound like stabbing or gunshot"},
                        "comparators": ["in", "not_in"]},
                    "bp_all": {"label": "Body Parts", "type": "categorical", "comparators": ["in", "not_in"],
                        "values": [110, 120, 130, 135, 140, 141, 210, 220, 230, 240, 250, 310, 315, 321, 322, 324, 325,
                                   330, 410, 415, 420, 430, 440, 450, 460, 470, 510, 520, 530, 540, 550, 560, 570, 700,
                                   900, 999],
                        "code_labels": {110: "head including skull and scalp", 120: "face", 130: "internal mouth",
                                        135: "specific head injury", 140: "neck excluding spinal cord",
                                        141: "internal organs in the neck like trachea", 210: "cervical spine",
                                        220: "thoracic spine", 230: "lumber spine", 240: "sacrum or coccyx",
                                        250: "other on unspecified spine",
                                        310: "thorax, ribs, heart, lungs, armpits, trachea",
                                        315: "upper back excluding scapula",
                                        321: "abdomen including all abdominal organs", 322: "lower back",
                                        323: "pelvis including bladder, bottocks, genitals",
                                        324: "perineum, external genitalia, scrotum", 325: "groin",
                                        330: "unpecified back", 410: "shoulders, including scapula", 415: "clavicle",
                                        420: "upper arm", 430: "elbow", 440: "forearm", 450: "wrist", 460: "hand",
                                        470: "finger or thumb", 510: "hip, including neck of femur",
                                        520: "thigh, including femur", 530: "knee", 540: "lower leg", 550: "ankle",
                                        560: "foot", 570: "toe", 700: "multiple injuries spanning multipe sections",
                                        900: "no specific body part including systemic injuries",
                                        999: "unspecified body part or no injury"}}, "sub": {"label" "Substance"
                                                                                             "type": "categorical",
                        "values": [1, 2], "code_labels": {1: "No substances involved", 2: "Substances involved", },
                        "comparators": ["eq", "neq"]},
                    "sub_id": {"label": "Substance ID", "type": "categorical", "comparators": ["like", "not_like"]},
                    "disp": {"label": "Disposition", "type": "categorical", "values": [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        "code_labels": {1: "LAMA", 2: "Advice Only", 3: "Treatment in ER w/ PRN follow-up",
                                        4: "Observation in ER w/ PRN follow-up", 5: "Observation in ER w/ follow-up",
                                        6: "Treatment with referral for injury", 7: "Admission for injury",
                                        8: "Admission for other reasons", 9: "DOA or died in ED"},
                        "comparators": ["eq", "neq", "in", "not_in"]}}}}
