from medspacy.ner import TargetRule

#TODO need a way to add to this
substances = [
    TargetRule(literal="alcohol",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["alchohol", "etoh", "vodka", "rum", "beer", "tequila", "drunk", "wine"
                                                                                                          "passed out"]}}]),
    TargetRule(literal="rec drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['cannabinoid', 'cannabinoids', 'cannabis', 'cbd', 'cocaine', 'crack cocaine', 'crack',
                          'downers', 'ecstasy', 'edible', 'edibles', 'got high', 'heroin', 'heroine', 'lsd', 'mdma',
                          'meth', 'methamphetamine', 'molly', 'morphine', 'mushroom', 'mushrooms', 'n-bomb', 'opioid',
                          'poppers', 'poppers', 'pot', 'psilocybin', 'recreational drugs', 'shrooms',
                          'stoner patch',
                          'street drugs', 'tetrahydrocannabinol', 'thc choclate', 'thc gummies', 'thc', 'uppers',
                          'weed', ]}}]),
    TargetRule(literal="household",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetone', 'after shave', 'ammonia', 'baby oil', 'bait', 'bio-oil', 'black locust tree bean',
                          'bleach', 'body wash', 'borax', 'callus remover', 'camphor', 'carbon monoxide',
                          'chloraseptic spray', 'chlorine', 'citronella', 'cleaner', 'cleaning products',
                          'coffee beans', 'conditioner', 'cream', 'degreaser', 'deodorant', 'detergent', 'dettol',
                          'diaper cream', 'drano', 'essential oil', 'essential oils', 'eucalyptus oil', 'febreze',
                          'foot powder', 'glow stick', 'h2o2', 'household cleaner', 'icy hot', 'isopropanol',
                          'isopropyl alcohol', 'lilly of the valley', 'lysol', 'methanol', 'moisturizer', 'moth balls',
                          'mouthwash', 'mr clean', 'nail polish', 'naphtaline', 'oxyclean', 'paint', 'perfume',
                          'peroxide', 'petrolatum', 'pine sol', 'poison', 'propane', 'raccoon feces', 'road salt',
                          'rubbing alcohol', 'sanitizer', 'shampoo', 'silica', 'silicagel', 'soap', 'soap',
                          'stain remover',
                          'tide pod', 'tide', 'toilet bowl cleaner', 'vicks', 'windex', 'witch hazel',
                          'yew berry', ]}}]),
    TargetRule(literal="tobacco",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ["cigarettes", "smoke", "hookah", "shisha", "vape", "vaping", "vaporizer", "nicotine",
                          "nicorette", "grabba, cigar", "tobacco"]}}]),
    TargetRule(literal="oc drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetaminophen', 'acetylsalicylic acid', 'advil', 'alleve', 'anti acid', 'antiacid',
                          'antihistamine', 'apple cider pills', 'aspirin', 'benadryl', 'betaine', 'caffeine',
                          'childrens tylenol', 'claritin', 'cold fx', 'cold medication', 'cold medications',
                          'cough medications', 'cough syrup', 'dihpnehydramine', 'dimenhydrinate', 'ex-lax',
                          'feramax', 'ferrous sulfate pills', 'flu medication', 'gaviscon', 'gravol', 'guaifenesin',
                          'hydroxyzine', 'ibuprofen', 'indomethacin', 'iron', 'lactulose', 'laxatives', 'lidocaine',
                          'loperamide', 'magnesium', 'melatonin', 'midol', 'motrin', 'multi vitamin', 'multi-vitamins',
                          'multivitamin', 'nyquil', 'olbas', 'paracetamol', 'polysporin', 'pseudoephrine', 'reactine',
                          'restorlax', 'robutussin', 'salicylate', 'senokot', 'sinutab', 'supplements', 'tylenol',
                          'valproic acid', 'vitamin d', 'vitamins', 'voltaren', 'zquil', ]}}]),

    TargetRule(literal="pres drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["adderall", "adhd medication", "alprazolam", "alysena", "amitriptyline",
                                          "amlodipine", "amoxicillin", "amphetamine", "antidepressant", "aripiprazole",
                                          "atenolol", "ativan", "atomoxetine", "azilsartan", "baclofen", "benzocaine",
                                          "benzodiazepines", "benzos", "biphentin", "bisoprolol",
                                          "blood pressure medications",
                                          "brotizolam", "bupropion", "cantharidin", "carbamazepine", "carbidopa",
                                          "carvedilol",
                                          "cetirizine", "chlorpheniramine", "cipralex", "citalopram", "clavulin",
                                          "clobazam",
                                          "clonazepam", "clonidine", "clopidogrel", "codeine", "colchicine", "concerta",
                                          "crestor", "crystal meth", "cyclobenzaprine", "dexamethasone",
                                          "dextromethorphan",
                                          "diazepam", "dilaudid", "diphenhydramine", "domperidone", "duloxetine",
                                          "effexor",
                                          "ephedrine", "epi pen", "epinephrine", "epipen", "escitalopram", "estrogen",
                                          "fentanyl", "fluconazole", "fluoxetine", "fosinopril", "gabapentin",
                                          "guanfacine",
                                          "hydrochlorothiazide", "hydromorphone", "insulin", "intuniv", "jenuvia",
                                          "keflex",
                                          "keppra", "lacosamide", "lamotrigine", "lansoprazole", "levetiracetam",
                                          "levocarnitine",
                                          "levodopa", "levothyroxine", "lisdexafetamine", "lisdexamfetamine",
                                          "lisdexamfetamine",
                                          "lithium", "lithium carbonate", "lorazepam", "lupron", "lyrica", "memantine",
                                          "methadone", "methocarbamol", "methotrexate", "methylphenidate", "modafinil",
                                          "muloxicom", "naltrexone", "naproxen", "napthalene", "nitrofurantoin",
                                          "nortriptyline",
                                          "olanzapine", "olanzapine", "ondansetron", "oxcarbazepine", "oxivir",
                                          "oxycocet",
                                          "oxycodone", "paliperidone", "palytoxin", "pantoloc", "perampanel",
                                          "percocet",
                                          "perindopril", "phenytoin", "prazosin", "pregabalin", "prescription",
                                          "progestin",
                                          "prozac", "quetiapine", "rabeprazole", "rupall", "senokot", "seroquel",
                                          "sertraline",
                                          "silenor", "somatropin", "speeping medication", "spironolactone", "synthroid",
                                          "tamoxifen", "tamsulosin", "tegretol", "tetracaine", "tramadol", "tranexamic",
                                          "trazadone", "trimebutine", "trinazapine", "vyvanse", "wellbutrin", "xanax",
                                          "zantax", "zoloft", "zolpidem", "zopiclone",
                                          ]}}]),

    TargetRule(literal="unknown",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["unknown", "unspecified"]}},
                        {"LOWER": {"IN": ["meds", "pills", "substance", "substances"]}}]),

]
