from medspacy.context import ConTextRule
from medspacy.ner import TargetRule

context_rules = context_rules = [
    ConTextRule(literal="?",
                category="POSSIBLE_EXISTENCE",
                direction="BIDIRECTIONAL",
                max_scope=1),
    ConTextRule(literal='not', category='NEGATED_EXISTENCE',
                pattern=[{'LOWER': {'IN': ["haven't", "didn't", "have", "did"]}},
                         {'LOWER': {'IN': ["not"]}},
                         {'LOWER': {'IN': ['appear', 'exihibit', 'demonstrate'
                                                                 'feel', 'reveal']}},
                         {"OP": "?"}], direction='FORWARD', max_scope=1),
    ConTextRule("DETECTED", category="POSSIBLE_EXISTENCE",
                direction="BACKWARD",
                max_scope=1),
    ConTextRule("NOT DETECTED", category="NEGATED_EXISTENCE",
                direction="BACKWARD",
                max_scope=1),
    ConTextRule(literal="not able", category="NEGATED_EXISTENCE",
                pattern=[{"LOWER": {"IN": ['not', "n't"]}},
                         {"LOWER": {"IN": ["can", "will", "could", "would", "won"]}}],
                direction="FORWARD", max_scope=2),
    ConTextRule(literal="x times", category="POSITIVE_EXISTENCE",
                pattern=[{'LOWER': {'IN': ["x"]}},
                         {'LOWER': {'IN': [str(x) for x in range(10)]}}],
                direction="BACKWARD", max_scope=3),
    ConTextRule(literal="times x", pattern=[{"LOWER": {"IN": [str(x) for x in range(10)]}},
                                            {"LOWER": {"IN": ["x"]}}],
                direction="BACKWARD", max_scope=2, category="POSITIVE_EXISTENCE", ),
    ConTextRule(literal="x times", pattern=[{'LOWER': {'IN': [str(x) for x in range(10)]}},
                                            {"LOWER": {"IN": ["times"]}}],
                category="POSITIVE_EXISTENCE", direction="BACKWARD", max_scope=3),
    ConTextRule(literal="x regex", pattern=[{'LOWER': {'REGEX': "[0-9]x"}}],
                category="POSITIVE_EXISTENCE", direction="BIDIRECTIONAL", max_scope=3),
    ConTextRule(literal="regex x", pattern=[{'LOWER': {'REGEX': "x[0-9]"}}],
                category="POSITIVE_EXISTENCE", direction="BIDIRECTIONAL", max_scope=3),
    ConTextRule(literal="fh", category="FAMILY", direction="FORWARD"),
    ConTextRule(literal="episodes", category="POSITIVE_EXISTENCE", direction="FORWARD", max_scope=4,
                pattern=[{"LOWER": {'IN': ["episodes", "episodes of", "continued", "episode"]}}]),
    ConTextRule(literal="reported", category="POSITIVE_EXISTENCE", direction="FORWARD"),
    ConTextRule(literal="feels", category="POSSIBLE_EXISTENCE", direction="FORWARD",
                pattern=[{"LOWER": {"IN": ["feels"]}},
                         {"LOWER": {"IN": ["like"]}}]),
    ConTextRule(literal="past", category="HISTORICAL", direction="FORWARD", max_scope=2),
    ConTextRule(literal="presenting", category="POSITIVE_EXISTENCE", direction="FORWARD", max_scope=10),
    # arbitrary, don't wanna over/under do
    ConTextRule(literal="some", category="POSITIVE_EXISTENCE", direction="FORWARD", max_scope=1),
    # arbitrary, don't wanna over/under do
    ConTextRule(literal="here with", category="POSITIVE_EXISTENCE", direction="FORWARD"),
    # ConTextRule(literal="complains", category="POSITIVE_EXISTENCE", direction="FORWARD", pattern=[{"LOWER":{"IN":["complains", "complained"]}}]),
    ConTextRule(literal="diagnosis", category="POSITIVE_EXISTENCE",
                pattern=[{'LOWER': {'IN': ["diagnosed", "diagnosed with", "dx", "diagnosis"]}}],
                direction="FORWARD"),
    ConTextRule(literal="positive for", category="POSITIVE_EXISTENCE", direction="forward",
                pattern=[{"LOWER": {"IN": ["positivie"]}},
                         {"LOWER": {"IN": ["for"]}}]),
    ConTextRule(literal="parent says", category="POSITIVE_EXISTENCE",
                pattern=[{"LOWER": {"IN": ["parent", "parents", "mom", "dad", "father", "mother", "family"]}},
                         {"LOWER": {"IN": ["says", "states", "reports", "report", "say", "state", "is aware"]}}],
                direction="FORWARD", max_scope=10),
    ConTextRule(" - ", "CONJ", direction="TERMINATE", pattern=[{"LOWER": {"IN": [" - ", " -", "- "]}}]),
    ConTextRule(";", "CONJ", direction="TERMINATE"),
    ConTextRule("(", "CONJ", direction="TERMINATE"),
    ConTextRule(")", "CONJ", direction="TERMINATE"),
    ConTextRule("no", direction="FORWARD", category="NEGATED_EXISTENCE", max_scope=5),
    # these are for bones joints cracking it is not meth
    ConTextRule("heard a crack", direction="FORWARD", category="NEGATED_EXISTENCE", max_scope=5),
    ConTextRule("something crack", direction="FORWARD", category="NEGATED_EXISTENCE", max_scope=5),
    ConTextRule("cracked", direction="FORWARD", category="NEGATED_EXISTENCE", max_scope=5),

    # ConTextRule(". ", "CONJ", direction="TERMINATE"),
    # ConTextRule(literal="parent states", category="POSITIVE_EXISTENCE",
    #           direction="FORWARD")
]

substance_rules = [
    TargetRule(literal="alcohol",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["alchohol", "etoh", "vodka", "rum", "beer", "tequila", "drunk", "wine", "OH"
                                                                                                                  "passed out"]}}]),
    TargetRule(literal="rec drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['cannabinoid', 'cannabinoids', 'cannabis', 'cbd', 'cocaine', 'crack cocaine', 'crack',
                          'downers', 'ecstasy', 'edible', 'edibles', 'got high', 'heroin', 'heroine', 'lsd', 'mdma',
                          'meth', 'methamphetamine', 'molly', 'morphine', 'mushroom', 'mushrooms', 'n-bomb', 'opioid',
                          'poppers', 'poppers', 'pot', 'psilocybin', 'recreational drugs', 'shrooms', 'stoner patch',
                          'street drugs', 'tetrahydrocannabinol', 'thc choclate', 'thc gummies', 'thc', 'uppers',
                          'weed', ]}}]),
    TargetRule(literal="household",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetone', 'after shave', 'ammonia', 'baby oil', 'bait', 'bio-oil', 'black locust tree bean',
                          'bleach', 'body wash', 'borax', 'callus remover', 'camphor', 'carbon monoxide',
                          'chloraseptic spray', 'chlorine', 'citronella', 'cleaner', 'cleaning products',
                          'coffee beans', 'conditioner', 'cream', 'degreaser', 'deodorant', 'detergent', 'dettol',
                          'diaper cream', 'drano', 'essential oil', 'essential oils', 'eucalyptus oil', 'febreze',
                          'foot powder', 'glow stick', 'h2o2', 'household cleaner', 'icy hot', 'isopropanol',
                          'isopropyl alcohol', 'lilly of the valley', 'lysol', 'methanol', 'moisturizer', 'moth balls',
                          'mouthwash', 'mr clean', 'nail polish', 'naphtaline', 'oxyclean', 'paint', 'perfume',
                          'peroxide', 'petrolatum', 'pine sol', 'poison', 'propane', 'raccoon feces', 'road salt',
                          'rubbing alcohol', 'sanitizer', 'shampoo', 'silica', 'silicagel', 'soap', 'soap',
                          'stain remover',
                          'tide pod', 'tide', 'toilet bowl cleaner', 'vicks', 'windex', 'witch hazel',
                          'yew berry', ]}}]),
    TargetRule(literal="tobacco",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ["cigarettes", "smoke", "hookah", "shisha", "vape", "vaping", "vaporizer", "nicotine",
                          "nicorette", "grabba, cigar", "tobacco"]}}]),
    TargetRule(literal="oc drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetaminophen', 'acetylsalicylic acid', 'advil', 'alleve', 'anti acid', 'antiacid',
                          'antihistamine', 'apple cider pills', 'aspirin', 'benadryl', 'betaine', 'caffeine',
                          'childrens tylenol', 'claritin', 'cold fx', 'cold medication', 'cold medications',
                          'cough medications', 'cough syrup', 'dihpnehydramine', 'dimenhydrinate', 'ex-lax',
                          'feramax', 'ferrous sulfate pills', 'flu medication', 'gaviscon', 'gravol', 'guaifenesin',
                          'hydroxyzine', 'ibuprofen', 'indomethacin', 'iron', 'lactulose', 'laxatives', 'lidocaine',
                          'loperamide', 'magnesium', 'melatonin', 'midol', 'motrin', 'multi vitamin', 'multi-vitamins',
                          'multivitamin', 'nyquil', 'olbas', 'paracetamol', 'polysporin', 'pseudoephrine', 'reactine',
                          'restorlax', 'robutussin', 'salicylate', 'senokot', 'sinutab', 'supplements', 'tylenol',
                          'valproic acid', 'vitamin d', 'vitamins', 'voltaren', 'zquil', ]}}]),

    TargetRule(literal="pres drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["adderall", "adhd medication", "alprazolam", "alysena", "amitriptyline",
                                          "amlodipine", "amoxicillin", "amphetamine", "antidepressant", "aripiprazole",
                                          "atenolol", "ativan", "atomoxetine", "azilsartan", "baclofen", "benzocaine",
                                          "benzodiazepines", "benzos", "biphentin", "bisoprolol",
                                          "blood pressure medications",
                                          "brotizolam", "bupropion", "cantharidin", "carbamazepine", "carbidopa",
                                          "carvedilol",
                                          "cetirizine", "chlorpheniramine", "cipralex", "citalopram", "clavulin",
                                          "clobazam",
                                          "clonazepam", "clonidine", "clopidogrel", "codeine", "colchicine", "concerta",
                                          "crestor", "crystal meth", "cyclobenzaprine", "dexamethasone",
                                          "dextromethorphan",
                                          "diazepam", "dilaudid", "diphenhydramine", "domperidone", "duloxetine",
                                          "effexor",
                                          "ephedrine", "epi pen", "epinephrine", "epipen", "escitalopram", "estrogen",
                                          "fentanyl", "fluconazole", "fluoxetine", "fosinopril", "gabapentin",
                                          "guanfacine",
                                          "hydrochlorothiazide", "hydromorphone", "insulin", "intuniv", "jenuvia",
                                          "keflex",
                                          "keppra", "lacosamide", "lamotrigine", "lansoprazole", "levetiracetam",
                                          "levocarnitine",
                                          "levodopa", "levothyroxine", "lisdexafetamine", "lisdexamfetamine",
                                          "lisdexamfetamine",
                                          "lithium", "lithium carbonate", "lorazepam", "lupron", "lyrica", "memantine",
                                          "methadone", "methocarbamol", "methotrexate", "methylphenidate", "modafinil",
                                          "muloxicom", "naltrexone", "naproxen", "napthalene", "nitrofurantoin",
                                          "nortriptyline",
                                          "olanzapine", "olanzapine", "ondansetron", "oxcarbazepine", "oxivir",
                                          "oxycocet",
                                          "oxycodone", "paliperidone", "palytoxin", "pantoloc", "perampanel",
                                          "percocet",
                                          "perindopril", "phenytoin", "prazosin", "pregabalin", "prescription",
                                          "progestin",
                                          "prozac", "quetiapine", "rabeprazole", "rupall", "senokot", "seroquel",
                                          "sertraline",
                                          "silenor", "somatropin", "speeping medication", "spironolactone", "synthroid",
                                          "tamoxifen", "tamsulosin", "tegretol", "tetracaine", "tramadol", "tranexamic",
                                          "trazadone", "trimebutine", "trinazapine", "vyvanse", "wellbutrin", "xanax",
                                          "zantax", "zoloft", "zolpidem", "zopiclone", "ritalin"
                                          ]}}]),

    TargetRule(literal="unknown",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["unknown", "unspecified"]}},
                        {"LOWER": {"IN": ["meds", "pills", "substance", "substances"]}}]),

]
