from medspacy.ner import TargetRule

body_parts = [

    TargetRule(literal="110",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["head", "scalp", "skull"]}},
                        {"LOWER": {"NOT_IN": ["radial", "forehead"]}}
                        ]),
    TargetRule(literal="120",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["mandible", "face", "eyelid", "periocular", "ear", "nose", "mouth",
                                          "jaw", "nasal", "facial", "chin", "cheek", "eyebrow", "lip",
                                          "forehead", "sinus", "orbital", "epistaxis", "tympanic"]}},
                        {"LOWER": {"NOT_IN": ["surface", "forearm", "frenulum"]}}
                        ]),
    TargetRule(literal="130",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["internal", "mouth", "tongue"]}},
                        ]),
    TargetRule(literal="135",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["skull", "sphenoid", "parietal", "occipital", "toot", "teeth",
                                          "eye", "cornea", "ocular", "globe", "ear", "nose", "nasal",
                                          "earlobe", "dental", ]}},
                        ]),
    TargetRule(literal="140",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["neck", ]}},
                        {"LOWER": {"NOT_IN": ["spine", "spinal cord"]}}
                        ]),
    TargetRule(literal="141",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["esophagial", "esophagus", "trachea", "pharyngeal", "laryngeal"]}},
                        ]),
    TargetRule(literal="210",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["cervical"]}},
                        ]),
    TargetRule(literal="220",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thoracic"]}},
                        ]),
    TargetRule(literal="230",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["lumbar"]}},
                        ]),

    TargetRule(literal="240",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["sarcum", "coccyx"]}},
                        ]),
    TargetRule(literal="250",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["spine"]}},
                        ]),
    TargetRule(literal="310",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thorax", "ribs", "lungs", "armpits", "lower esophagus", "trachea",
                                          "chest"]}},
                        ]),
    TargetRule(literal="315",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["upper back", "trapezoid"]}},
                        ]),

    TargetRule(literal="321",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["abdomen", "abdominal", "colon", "intestine", "stomach", "kidney",
                                          "spleen", "gi", "gastrointestinal", "liver"]}},
                        ]),
    TargetRule(literal="322",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["lower back", "flank"]}},
                        ]),
    TargetRule(literal="323",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["bladder", "buttocks", "rectum", "vagina", "labia", "anal", "vulva"]}},
                        ]),
    TargetRule(literal="324",
               category="BODY_PART",
               pattern=[
                   {"LOWER": {"IN": ["penis", "scrotum", "testes", "testis", "testicular", "circumcision", "penile"]}},
                   ]),
    TargetRule(literal="325",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["groin"]}},
                        ]),
    TargetRule(literal="330",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["back"]}},
                        ]),
    TargetRule(literal="410",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["shoulder", "scapula", "proximal humerus", "proximal humeral"]}},
                        ]),
    TargetRule(literal="415",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["clavicle", "clavical", ]}},
                        ]),
    TargetRule(literal="420",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["upper arm", "humerus"]}},
                        {"LOWER": {"NOT_IN": ["condyl", "distal", "proximal"]}}
                        ]),
    TargetRule(literal="430",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["elbow", "distal humerus", "distal humeral", "condyl", "ulna", "radius"
                                                                                                         "proximal radius",
                                          "proximal ulna", "olecranon"]}}
                        ]),
    TargetRule(literal="440",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["forearm", "condyl", "ulna", "radius", "monteggia", "lower arm", "arm"]}},
                        {"LOWER": {"NOT_IN": ["upper", "distal", "proximal"]}}
                        ]),
    TargetRule(literal="450",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["wrist", "carpal", "distal radius", "distal ulna"]}}]),

    TargetRule(literal="460",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["hand", "metacarpal"]}}]),

    TargetRule(literal="470",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["finger", "thumb"]}},
                        {"LOWER": {"NOT_IN": ["toe", "foot"]}}
                        ]),

    TargetRule(literal="510",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["hip", "neck of femur", "proximal femur"]}},
                        ]),
    TargetRule(literal="520",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thigh", "femur", "femoral"]}},
                        ]),
    TargetRule(literal="530",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["knee", "distal femur", "distal femoral", "proximal tibia",
                                          "proximal fibula"]}},
                        ]),
    TargetRule(literal="540",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["tibia", "fibula", "lower leg", "patella"]}},
                        ]),
    TargetRule(literal="550",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["ankle", "tarsal", "distal fibula", "distal tibia"]}},
                        ]),
    TargetRule(literal="560",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["foot", "metatarsal"]}},
                        {"LOWER": {
                            "NOT_IN": ["phalanges", "phalanx", "toe", "high", "height", "distance", "distance of",
                                       "height of",
                                       "away"]}}
                        ]),
    TargetRule(literal="570",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["toe"]}}
                        ]),
    TargetRule(literal="ST",  # soft tissue this is for foreign bodies only
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["skin", "earlobe", "tissue", "soft tissue"]}}
                        ]),

]

injuries = [
    TargetRule(literal="10",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["subungual", "hematoma", "abrasion", "bruise", "contusion" "superficial"]}},
                        {"LOWER": {
                            "NOT_IN": ["globe", "cornea", "ocular", "eye", "cut", "laceration", "burn", "swelling"
                                                                                                        "kidney",
                                       "liver", "spleen", "splenic"]}}
                        ]),
    TargetRule(literal="11",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["open wound", "wound", "laceration", "cut", "minor laceration", "nail",
                                          "avulsion", "circumcision", "fissure", "epistaxis", "self cut", "nose bleed",
                                          "dehiscence", "tear"]}},
                        {"LOWER": {"NOT_IN": ["liver", "spleen", "splenic"]}}]),
    TargetRule(literal="12",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["fracture", "fx", "broken", ]}},
                        {"LOWER": {"NOT_IN": ["broken tooth", "broke tooth", "broken teeth", "broke teeth",
                                              "chipped tooth", "chipped teeth", "dental"]}}
                        ]),

    TargetRule(literal="13",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["dislocation", "subluxation", "spine", "spinal"]}},
                        ]),

    TargetRule(literal="14",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["sprain", "strain"]}}]),

    TargetRule(literal="15",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["nerve", "palsy"]}},
                        {"LOWER": {"NOT_IN": ["edema", "oedema"]}}
                        ]),

    TargetRule(literal="16",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["blood vessel", "hemorrhage"]}}
                        ]),

    TargetRule(literal="17",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["tendon", "muscle", "rupture", "sever", "muscle tendon", "muscle rupture"]}},
                        ]),

    TargetRule(literal="18",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["crush"]}}
                        ]),

    TargetRule(literal="19",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["amputation"]}}
                        ]),

    TargetRule(literal="20",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["corrosion", "burn", ""]}},
                        {"LOWER": {"NOT_IN": ["globe", "cornea", "ocular", "eye"]}}
                        ]),
    TargetRule(literal="21",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["frostbite"]}}
                        ]),
    TargetRule(literal="22",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["bite"]}}
                        ]),
    TargetRule(literal="23",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["electric", "electrical", "electric shock"]}},
                        ]),
    TargetRule(literal="24",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["globe", "cornea", "ocular", "eye", "visual disturbance", "vision loss"]}},
                        {"LOWER": {"NOT_IN": ["hallucination", "foreign", "fb", "inserted"]}}  # 135
                        ]),
    TargetRule(literal="25",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["broken tooth", "broke tooth", "broken teeth", "broke teeth",
                                          "chipped tooth", "chipped teeth", "dental", "dental implant"]}},
                        ]),
    TargetRule(literal="26",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["heart", "liver", "lung", "kidney", "stomach", "spleen", "perforated",
                                          "ear canal"]}},
                        ]),
    TargetRule(literal="27",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["soft tissue", "swelling", "torsion"]}},
                        {"LOWER": {"NOT_IN": ["sickle", "cyst", "mass", "foreign", "fb"]}},
                        ]),
    TargetRule(literal="3X",  # all foreign bodies, the result will depend on body parts
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["foreign", "fb", "foreign body", "splinter", "hair tourniquet"]}},
                        # 31, 32, 32 all return 135
                        ]),
    TargetRule(literal="41",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["minor head"]}}]),  # 135

    TargetRule(literal="42",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["concussion"]}},  # 135
                        ]),
    TargetRule(literal="43",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["intercranial"]}},
                        {"LOWER": {"NOT_IN": ["cancer", "tumor", "tumour", "mass"]}},
                        ]),
    TargetRule(literal="50",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["poison", "toxic", "overdose", "overdose ingestion", "substance misuse"]}}]),
    TargetRule(literal="51",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["drown", "immersion"]}}]),  # 900
    TargetRule(literal="52",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["asphyxia", "choking"]}}]),  # 900
    TargetRule(literal="53",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["heat stress", "cold stress", "hypothermia", "hyperthermia",
                                          "overexertion"]}}]),  # 900
    TargetRule(literal="70",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["no injury"]}}]),

    TargetRule(literal="75",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["pulled elbow", "nursemaid"]}}]),  # 430

    TargetRule(literal="76",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["corrosive", "caustic", "bleach", "detergent", "chemical"]}}]),

    TargetRule(literal="77",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["stab", "stabbing", "bullet", "stabbed", "penetrating"]}}]),
    # 71 is mental health with 900

]

substances = [
    TargetRule(literal="alcohol",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["alchohol", "etoh", "vodka", "rum", "beer", "tequila", "drunk", "wine"
                                                                                                          "passed out"]}}]),
    TargetRule(literal="rec drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['cannabinoid', 'cannabinoids', 'cannabis', 'cbd', 'cocaine', 'crack cocaine', 'crack',
                          'downers', 'ecstasy', 'edible', 'edibles', 'got high', 'heroin', 'heroine', 'lsd', 'mdma',
                          'meth', 'methamphetamine', 'molly', 'morphine', 'mushroom', 'mushrooms', 'n-bomb', 'opioid',
                          'pcp', 'poppers', 'poppers', 'pot', 'psilocybin', 'recreational drugs', 'shrooms',
                          'stoner patch',
                          'street drugs', 'tetrahydrocannabinol', 'thc choclate', 'thc gummies', 'thc', 'uppers',
                          'weed', ]}}]),
    TargetRule(literal="household",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetone', 'after shave', 'ammonia', 'baby oil', 'bait', 'bio-oil', 'black locust tree bean',
                          'bleach', 'body wash', 'borax', 'callus remover', 'camphor', 'carbon monoxide',
                          'chloraseptic spray', 'chlorine', 'citronella', 'cleaner', 'cleaning products',
                          'coffee beans', 'conditioner', 'cream', 'degreaser', 'deodorant', 'detergent', 'dettol',
                          'diaper cream', 'drano', 'essential oil', 'essential oils', 'eucalyptus oil', 'febreze',
                          'foot powder', 'glow stick', 'h2o2', 'household cleaner', 'icy hot', 'isopropanol',
                          'isopropyl alcohol', 'lilly of the valley', 'lysol', 'methanol', 'moisturizer', 'moth balls',
                          'mouthwash', 'mr clean', 'nail polish', 'naphtaline', 'oxyclean', 'paint', 'perfume',
                          'peroxide', 'petrolatum', 'pine sol', 'poison', 'propane', 'raccoon feces', 'road salt',
                          'rubbing alcohol', 'sanitizer', 'shampoo', 'silica', 'silicagel', 'soap', 'soap',
                          'stain remover',
                          'tide pod', 'tide', 'toilet bowl cleaner', 'vicks', 'windex', 'witch hazel',
                          'yew berry', ]}}]),
    TargetRule(literal="tobacco",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ["cigarettes", "smoke", "hookah", "shisha", "vape", "vaping", "vaporizer", "nicotine",
                          "nicorette", "grabba, cigar", "tobacco"]}}]),
    TargetRule(literal="oc drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {
                   "IN": ['acetaminophen', 'acetylsalicylic acid', 'advil', 'alleve', 'anti acid', 'antiacid',
                          'antihistamine', 'apple cider pills', 'aspirin', 'benadryl', 'betaine', 'caffeine',
                          'childrens tylenol', 'claritin', 'cold fx', 'cold medication', 'cold medications',
                          'cough medications', 'cough syrup', 'dihpnehydramine', 'dimenhydrinate', 'ex-lax',
                          'feramax', 'ferrous sulfate pills', 'flu medication', 'gaviscon', 'gravol', 'guaifenesin',
                          'hydroxyzine', 'ibuprofen', 'indomethacin', 'iron', 'lactulose', 'laxatives', 'lidocaine',
                          'loperamide', 'magnesium', 'melatonin', 'midol', 'motrin', 'multi vitamin', 'multi-vitamins',
                          'multivitamin', 'nyquil', 'olbas', 'paracetamol', 'polysporin', 'pseudoephrine', 'reactine',
                          'restorlax', 'robutussin', 'salicylate', 'senokot', 'sinutab', 'supplements', 'tylenol',
                          'valproic acid', 'vitamin d', 'vitamins', 'voltaren', 'zquil', ]}}]),

    TargetRule(literal="pres drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["adderall", "adhd medication", "alprazolam", "alysena", "amitriptyline",
                                          "amlodipine", "amoxicillin", "amphetamine", "antidepressant", "aripiprazole",
                                          "atenolol", "ativan", "atomoxetine", "azilsartan", "baclofen", "benzocaine",
                                          "benzodiazepines", "benzos", "biphentin", "bisoprolol",
                                          "blood pressure medications",
                                          "brotizolam", "bupropion", "cantharidin", "carbamazepine", "carbidopa",
                                          "carvedilol",
                                          "cetirizine", "chlorpheniramine", "cipralex", "citalopram", "clavulin",
                                          "clobazam",
                                          "clonazepam", "clonidine", "clopidogrel", "codeine", "colchicine", "concerta",
                                          "crestor", "crystal meth", "cyclobenzaprine", "dexamethasone",
                                          "dextromethorphan",
                                          "diazepam", "dilaudid", "diphenhydramine", "domperidone", "duloxetine",
                                          "effexor",
                                          "ephedrine", "epi pen", "epinephrine", "epipen", "escitalopram", "estrogen",
                                          "fentanyl", "fluconazole", "fluoxetine", "fosinopril", "gabapentin",
                                          "guanfacine",
                                          "hydrochlorothiazide", "hydromorphone", "insulin", "intuniv", "jenuvia",
                                          "keflex",
                                          "keppra", "lacosamide", "lamotrigine", "lansoprazole", "levetiracetam",
                                          "levocarnitine",
                                          "levodopa", "levothyroxine", "lisdexafetamine", "lisdexamfetamine",
                                          "lisdexamfetamine",
                                          "lithium", "lithium carbonate", "lorazepam", "lupron", "lyrica", "memantine",
                                          "methadone", "methocarbamol", "methotrexate", "methylphenidate", "modafinil",
                                          "muloxicom", "naltrexone", "naproxen", "napthalene", "nitrofurantoin",
                                          "nortriptyline",
                                          "olanzapine", "olanzapine", "ondansetron", "oxcarbazepine", "oxivir",
                                          "oxycocet",
                                          "oxycodone", "paliperidone", "palytoxin", "pantoloc", "perampanel",
                                          "percocet",
                                          "perindopril", "phenytoin", "prazosin", "pregabalin", "prescription",
                                          "progestin",
                                          "prozac", "quetiapine", "rabeprazole", "rupall", "senokot", "seroquel",
                                          "sertraline",
                                          "silenor", "somatropin", "speeping medication", "spironolactone", "synthroid",
                                          "tamoxifen", "tamsulosin", "tegretol", "tetracaine", "tramadol", "tranexamic",
                                          "trazadone", "trimebutine", "trinazapine", "vyvanse", "wellbutrin", "xanax",
                                          "zantax", "zoloft", "zolpidem", "zopiclone",
                                          ]}}]),

    TargetRule(literal="unknown",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN": ["unknown", "unspecified"]}},
                        {"LOWER": {"IN": ["meds", "pills", "substance", "substances"]}}]),

]
