from medspacy.ner import TargetRule

body_parts=[

    TargetRule(literal="110",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["head", "scalp", "skull"]}},
                        {"LOWER": {"NOT_IN": ["radial", "forehead"]}}
                        ]),
    TargetRule(literal="120",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["mandible", "face", "eyelid", "periocular", "ear", "nose", "mouth",
                                          "jaw", "nasal", "facial", "chin", "cheek", "eyebrow", "lip",
                                          "forehead", "sinus", "orbital", "epistaxis", "tympanic"]}},
                        {"LOWER": {"NOT_IN": ["surface", "forearm", "frenulum"]}}
                        ]),
    TargetRule(literal="130",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["internal", "mouth", "tongue"]}},
                        ]),
    TargetRule(literal="135",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["skull", "sphenoid", "parietal", "occipital", "toot", "teeth",
                                          "eye", "cornea", "ocular", "globe", "ear", "nose", "nasal",
                                          "earlobe", "dental", ]}},
                        ]),
    TargetRule(literal="140",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["neck", ]}},
                        {"LOWER": {"NOT_IN": ["spine", "spinal cord"]}}
                        ]),
    TargetRule(literal="141",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["esophagial", "esophagus", "trachea", "pharyngeal", "laryngeal"]}},
                        ]),
    TargetRule(literal="210",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["cervical"]}},
                        ]),
    TargetRule(literal="220",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thoracic"]}},
                        ]),
    TargetRule(literal="230",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["lumbar"]}},
                        ]),

    TargetRule(literal="240",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["sarcum", "coccyx"]}},
                        ]),
    TargetRule(literal="250",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["spine"]}},
                        ]),
    TargetRule(literal="310",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thorax", "ribs", "lungs", "armpits", "lower esophagus", "trachea",
                                          "chest"]}},
                        ]),
    TargetRule(literal="315",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["upper back", "trapezoid"]}},
                        ]),

    TargetRule(literal="321",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["abdomen", "abdominal", "colon", "intestine", "stomach", "kidney",
                                          "spleen", "gi", "gastrointestinal", "liver"]}},
                        ]),
    TargetRule(literal="322",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["lower back", "flank"]}},
                        ]),
    TargetRule(literal="323",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["bladder", "buttocks", "rectum", "vagina", "labia", "anal", "vulva"]}},
                        ]),
    TargetRule(literal="324",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["penis", "scrotum", "testes", "testis", "testicular", "circumcision"]}},
                        ]),
    TargetRule(literal="325",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["groin"]}},
                        ]),
    TargetRule(literal="330",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["back"]}},
                        ]),
    TargetRule(literal="410",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["shoulder", "scapula", "proximal humerus", "proximal humeral"]}},
                        ]),
    TargetRule(literal="415",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["clavicle", "clavical",]}},
                        ]),
    TargetRule(literal="420",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["upper arm", "humerus"]}},
                        {"LOWER": {"NOT_IN": ["condyl", "distal", "proximal"]}}
                        ]),
    TargetRule(literal="430",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["elbow", "distal humerus", "distal humeral", "condyl", "ulna", "radius"
                                          "proximal radius", "proximal ulna", "olecranon"]}}
                        ]),
    TargetRule(literal="440",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["forearm", "condyl", "ulna", "radius", "monteggia", "lower arm", "arm"]}},
                        {"LOWER": {"NOT_IN": ["upper", "distal", "proximal"]}}
                        ]),
    TargetRule(literal="450",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["wrist", "carpal", "distal radius", "distal ulna"]}}]),

    TargetRule(literal="460",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["hand", "metacarpal", "phalanges"]}}]),

    TargetRule(literal="470",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["finger", "thumb"]}},
                        {"LOWER": {"NOT_IN": ["toe", "foot"]}}
                        ]),

    TargetRule(literal="510",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["hip", "neck of femur", "proximal femur"]}},
                        ]),
    TargetRule(literal="520",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["thigh", "femur", "femoral"]}},
                        ]),
    TargetRule(literal="530",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["knee", "distal femur", "distal femoral", "proximal tibia",
                                          "proximal fibula"]}},
                        ]),
    TargetRule(literal="540",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["tibia", "fibula", "lower leg", "patella"]}},
                        ]),
    TargetRule(literal="550",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["ankle", "tarsal", "distal fibula", "distal tibia"]}},
                        ]),
    TargetRule(literal="560",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["foot", "metatarsal"]}},
                        {"LOWER": {"NOT_IN": ["phalan", "toe", "high", "height", "distance", "distance of", "height of",
                                              "away"]}}
                        ]),
    TargetRule(literal="570",
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["phalan", "toe"]}}
                        ]),
    TargetRule(literal="ST", #soft tissue this is for foreign bodies only
               category="BODY_PART",
               pattern=[{"LOWER": {"IN": ["skin", "earlobe", "tissue", "soft tissue"]}}
                        ]),

]

injuries=[
    TargetRule(literal="10",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["subungual", "hematoma", "abrasion", "bruise", "contusion" "superficial"]}},
                        {"LOWER": {"NOT_IN": ["globe", "cornea", "ocular", "eye", "cut", "laceration", "burn", "swelling"
                                              "kidney", "liver", "spleen", "splenic"]}}
                        ]),
    TargetRule(literal="11",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["open wound", "wound", "laceration", "cut", "minor laceration", "nail",
                                          "avulsion", "circumcision", "fissure", "epistaxis", "self cut", "nose bleed",
                                          "dehiscence", "tear"]}},
                        {"LOWER": {"NOT_IN": ["liver", "spleen", "splenic"]}}]),
    TargetRule(literal="12",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["fracture", "fx", "broken", ]}},
                        {"LOWER": {"NOT_IN"["broken tooth", "broke tooth", "broken teeth", "broke teeth",
                                   "chipped tooth", "chipped teeth", "dental"]}}
                        ]),

    TargetRule(literal="13",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["dislocation", "subluxation", "spine", "spinal"]}},
                        ]),

    TargetRule(literal="14",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["sprain", "strain"]}}]),

    TargetRule(literal="15",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["nerve", "palsy"]}},
                        {"LOWER": {"NOT_IN": ["edema", "oedema"]}}
                        ]),

    TargetRule(literal="16",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["blood vessel", "hemorrhage"]}}
                        ]),

    TargetRule(literal="17",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["tendon", "muscle", "rupture", "sever", "muscle tendon", "muscle rupture"]}},
                        ]),

    TargetRule(literal="18",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["crush"]}}
                        ]),

    TargetRule(literal="19",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["amputation"]}}
                        ]),

    TargetRule(literal="20",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["corrosion", "burn", ""]}},
                        {"LOWER": {"NOT_IN": ["globe", "cornea", "ocular", "eye"]}}
                        ]),
    TargetRule(literal="21",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["frostbite"]}}
                        ]),
    TargetRule(literal="22",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["bite"]}}
                        ]),
    TargetRule(literal="23",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["electric", "electrical", "electric shock"]}},
                        ]),
    TargetRule(literal="24",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["globe", "cornea", "ocular", "eye", "visual disturbance", "vision loss"]}},
                        {"LOWER": {"NOT_IN":["hallucination", "foreign", "fb", "inserted"]}}
                        ]),
    TargetRule(literal="25",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["broken tooth", "broke tooth", "broken teeth", "broke teeth",
                                   "chipped tooth", "chipped teeth", "dental", "dental implant"]}},
                        ]),
    TargetRule(literal="26",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["heart", "liver", "lung", "kidney", "stomach", "spleen", "perforated",
                                          "ear canal"]}},
                        ]),
    TargetRule(literal="27",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["soft tissue", "swelling", "torsion"]}},
                        {"LOWER": {"NOT_IN":["sickle", "cyst", "mass", "foreign", "fb"]}},
                        ]),
    TargetRule(literal="3X", #all foreign bodies, the result will depend on body parts
               category="INJURY",
               pattern=[{"LOWER": {"IN":["foreign", "fb", "foreign body", "splinter", "hair tourniquet"]}},
                        ]),
    TargetRule(literal="41",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["minor head"]}}]),

    TargetRule(literal="42",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["concussion"]}},
                        ]),
    TargetRule(literal="43",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["intercranial"]}},
                        {"LOWER": {"NOT_IN": ["cancer", "tumor", "tumour", "mass"]}},
                        ]),
    TargetRule(literal="50",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["poison", "toxic", "overdose", "overdose ingestion", "substance misuse"]}}]),
    TargetRule(literal="51",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["drown", "immersion"]}}]),
    TargetRule(literal="52",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["asphyxia", "choking"]}}]),
    TargetRule(literal="53",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["heat stress", "cold stress", "hypothermia", "hyperthermia",
                                          "overexertion"]}}]),
    TargetRule(literal="70",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["no injury"]}}]),

    TargetRule(literal="75",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["pulled elbow", "nursemaid"]}}]),

    TargetRule(literal="76",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["corrosive", "caustic", "bleach", "detergent", "chemical"]}}]),

    TargetRule(literal="77",
               category="INJURY",
               pattern=[{"LOWER": {"IN": ["stab", "stabbing", "bullet", "stabbed", "penetrating"]}}]),
    #71 is mental health with 900

]

substances=[
    TargetRule(literal="alcohol",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["alchohol", "etoh", "vodka", "rum", "beer", "tequila", "drunk", "wine"
                                           "passed out"]}}]),
    TargetRule(literal="rec drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["cannabis", "weed", "pot", "edibles", 'thc gummies',
                                         "thc choclate", "ecstasy", "heroin", "n-bomb", "crack cocaine",
                                         "meth", "cocaine", "crack", "mdma", "street drugs", "recreational drugs",
                                         "shrooms", "mushrooms", "psilocybin", "lsd", "cbd", "cannabinoid", "molly",
                                         "got high", "uppers", "downers"]}}]),
    TargetRule(literal="household",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["acetone", "rubbing alcohol", "peroxide", "h2o2", "isopropanol",
                                         "after shave", "cleaner", "bio-oil", "essential oil", "bleach",
                                         "detergent", "tide", "callus remover", "chlorine", "cleaning products",
                                         "bait", 'poison', "diaper cream", "cream", "sanitizer", "icy hot", "vicks",
                                         "lysol", "mr clean", "mr. clean", "pine sol", "road salt", "silicagel", "silica"
                                         "soap", "windex", "witch hazel", "body wash", "borax", "drano", "naphtaline",
                                         "moth balls", "silicagel", "diaper cream", "shampoo", "conditioner", "moisturizer"]}}]),
    TargetRule(literal="tobacco",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["cigarettes", "smoke", "hookah", "shisha", "vape", "vaping", "vaporizer", "nicotine",
                                         "nicorette"]}}]),
    TargetRule(literal="oc drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["acetaminophen", "advil", "alleve", "antiacid", "anti acid", "apple cider pills",
                                         "aspirin", "benadryl", "betaine", "cold medication", "flu medication", "cough syrup",
                                         "ex-lax", "gravol", "iron", "supplements", "vitamins", "multi vitamins", "multivitamins",
                                         "multi-vitamins", "magnesium", "melatonin", "paracetamol", "restorlax", "robitussin",
                                         "tylenol", "senokot", "claritin", "antihistamine", "asprin", "caffeine", "ibuprofen"
                                         "midol", "salicylate"]}}]),

    TargetRule(literal="pres drugs",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["adderall", "alprazolam", "amitriptyline", "amlodipine",
                                         "amphetamine", "ativan", "baclofen", "benzocaine", "benzos", "biphentin",
                                         "blood pressure medications", "brotizolam", "bupropion", "cantharidin",
                                         "carbamazepine", "cetirizine", "chlorpheniramine", "cipralex", "citalopram",
                                         "clobazam", "clonazepam", "clopidogrel", "codeine", "colchicine", "concerta",
                                         "crestor", "crystal meth", "dilaudid", "diphenhydramine", "duloxetine",
                                         "ephedrine", "epinephrine", "epipen", "escitalopram", "fentanyl", "fluoxetine",
                                         "hydromorphone", "jenuvia", "keppra", "lansoprazole", "lisdexafetamine",
                                         "lithium carbonate", "lorazepam", "lyrica", "memantine", "methotrexate",
                                         "methylphenidate", "muloxicom", "naltrexone", "naproxen", "napthalene",
                                         "nitrofurantoin", "olanzapine", "oxcarbazepine", "oxivir", "oxycodone",
                                         "paliperidone", "palytoxin", "pantoloc", "perampanel", "percocet",
                                         "perindopril", "prazosin", "prozac", "quetiapine", "rupall", "senokot",
                                         "seroquel", "sertraline", "silenor", "somatropin", "speeping medication",
                                         "tetracaine", "trazodone", "vyvanse", "wellbutrin", "xanax", "zantax",
                                         "zoloft"]}}]),

    TargetRule(literal="unknown",
               category="SUBSTANCE",
               pattern=[{"LOWER": {"IN":["unknown", "unspecified"]}},
                        {"LOWER": {"IN":["meds", "pills", "substance", "substances"]}}]),

]
